#---# Metropolis Configuration File #---#
#       Configuration version 1.0       #

city:
  chat:
  
    # Should the city name be displayed in the chat?
    disp_city_name: true
  misc:
  
display:
  misc:
    
    # Default city name and description. Used in boundary displays and chat.
    def_name: 'Unnamed City'
    def_desc: 'No description given.' 
    
    # Rank tags. Two character max. Set to '' to disable.
    tag_mayor: '=='
    tag_officer: '='
    tag_landowner: '-'
    tag_member: ''
    
  color:
    # City name display colors.
    # These actually don't work at the moment, just showing the defaults for later use.
    color_standard: WHITE
    color_hostile: RED
    color_ally: GREEN
    color_admin: GOLD
    color_battle: DARK_RED
    
mechanics:
  gameplay:
    
  physics:
  
  econ:
    # Should Metropolis try to integrate with an economy plugin (BOSEconomy, iConomy, EssentialsEco, FairTrade, etc.)?
    enable_econ: false
	
    # If economy is enabled, how much should each city command cost?
    city_create: 20.0
    city_claim: 5.0
    city_claim_multiplier: 0.5
    city_announce: 0.0
    city_create_warp: 2.0
    city_warp: 0.0
	
    # When an area is unclaimed, how much should be refunded? (0.0 to 1.0)
    city_claim_refund_percent: 0.75
	
    # If economy is enabled, how much should each county command cost?
    county_create: 50.0
    county_announce: 0.0
    county_create_warp: 2.0
    county_warp: 0.0
  misc:
  
# END OF FILE.